name: CI

on:
  # Triggers the workflow on push events but for only the master branch
  push:
    branches:
      - master
  # Triggers the workflow on PR events but only when the master is the base
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Security audit
        run: npm run security
      - name: Linting source code
        run: npm run lint
    
  deploy:
    needs: [quality]
    runs-on: ubuntu-latest
    # only run this job on master branch -- prevents a deploy from happening every time a PR's branch is updated
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
